"""Static HTML report: data quality, yield KPIs and SPC, with charts inline."""

from __future__ import annotations

import base64
import html
import io
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

BLUE, ORANGE, RED, GREY = "#2f5d8a", "#d9822b", "#c0392b", "#8a8a8a"


def _fig_to_img(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=110, bbox_inches="tight")
    plt.close(fig)
    return f'<img alt="chart" src="data:image/png;base64,{base64.b64encode(buf.getvalue()).decode()}">'


def chart_station_yield(daily: pd.DataFrame) -> str:
    fig, ax = plt.subplots(figsize=(8, 3.2))
    for station, g in daily.groupby("station_id"):
        ax.plot(pd.to_datetime(g["test_day"]), g["pass_rate_7d_pct"], label=station)
    ax.set_ylabel("First-attempt pass rate, 7-day avg (%)")
    ax.legend(ncol=4, frameon=False)
    ax.grid(alpha=0.3)
    fig.autofmt_xdate()
    return _fig_to_img(fig)


def chart_pareto(pareto: pd.DataFrame) -> str:
    fig, ax = plt.subplots(figsize=(6, 3.2))
    ax.bar(pareto["bin_name"], pareto["fails"], color=BLUE)
    ax2 = ax.twinx()
    ax2.plot(pareto["bin_name"], pareto["cumulative_pct"], color=ORANGE, marker="o")
    ax2.set_ylim(0, 105)
    ax.set_ylabel("Failed tests")
    ax2.set_ylabel("Cumulative %")
    ax.tick_params(axis="x", labelrotation=12)
    return _fig_to_img(fig)


def chart_control(chart: pd.DataFrame, station: str) -> str:
    g = chart[chart["station_id"] == station]
    x = pd.to_datetime(g["test_day"])
    fig, ax = plt.subplots(figsize=(8, 3))
    ax.plot(x, g["geo_mean_ua"], marker="o", color=BLUE, label="Daily geometric mean")
    ax.step(x, g["ucl_ua"], where="mid", color=GREY, linestyle="--", label="Control limits")
    ax.step(x, g["lcl_ua"], where="mid", color=GREY, linestyle="--")
    ax.axhline(g["center_ua"].iloc[0], color=GREY, linewidth=1)
    alarm = g[g["out_of_control"]]
    ax.scatter(
        pd.to_datetime(alarm["test_day"]), alarm["geo_mean_ua"], color=RED, zorder=3, s=45, label="Alarm"
    )
    base_end = pd.to_datetime(g.loc[g["in_baseline"], "test_day"]).max()
    ax.axvspan(x.min(), base_end, color=GREY, alpha=0.1, label="Baseline")
    ax.set_title(f"Station {station}: leakage at 125 degC")
    ax.set_ylabel("Leakage (uA)")
    ax.legend(fontsize=8, frameon=False, ncol=2)
    ax.grid(alpha=0.3)
    fig.autofmt_xdate()
    return _fig_to_img(fig)


def _table(df: pd.DataFrame) -> str:
    return df.to_html(index=False, border=0, classes="t", na_rep="")


CSS = """
body{font-family:Arial,Helvetica,sans-serif;max-width:960px;margin:24px auto;padding:0 16px;color:#222}
h1{font-size:22px} h2{font-size:17px;border-bottom:1px solid #ccc;padding-bottom:4px;margin-top:28px}
.kpis{display:flex;gap:12px;flex-wrap:wrap}.kpi{border:1px solid #ddd;border-radius:6px;padding:10px 14px}
.kpi b{display:block;font-size:20px}.note{color:#555;font-size:13px}
table.t{border-collapse:collapse;font-size:12px;margin:8px 0}table.t th,table.t td{border-bottom:1px solid #e5e5e5;padding:4px 8px;text-align:left}
img{max-width:100%}
"""


def build_report(
    summary: dict,
    quality: pd.DataFrame,
    kpis: dict,
    chart: pd.DataFrame,
    alarms: pd.DataFrame,
    capability: pd.DataFrame,
    path: Path,
) -> Path:
    s = summary
    kpi_html = "".join(
        f'<div class="kpi">{html.escape(label)}<b>{value}</b></div>'
        for label, value in [
            ("Units", f"{s['units']:,}"),
            ("First-pass yield", f"{s['first_pass_yield_pct']:.2f} %"),
            ("Final yield (after retest)", f"{s['final_yield_pct']:.2f} %"),
            ("Rows in", f"{s['rows_in']:,}"),
            ("Duplicates dropped", f"{s['duplicates_dropped']:,}"),
            ("Rows quarantined", f"{s['rows_quarantined']:,}"),
        ]
    )
    if len(alarms):
        alarm_text = "; ".join(f"station {r.station_id} from {r.test_day}" for r in alarms.itertuples())
    else:
        alarm_text = "none"
    stations = sorted(chart["station_id"].unique()) if len(chart) else []
    control_imgs = "".join(chart_control(chart, st) for st in stations)
    worst_lots = kpis["v_lot_yield"].sort_values("first_pass_yield_pct").head(5)

    body = f"""
<h1>MCU End-of-Line Test Report</h1>
<p class="note">Synthetic data. Test period {s["period_start"]} to {s["period_end"]}. Generated by the pipeline run on seed {s["seed"]}.</p>
<div class="kpis">{kpi_html}</div>

<h2>1. Data quality</h2>
<p class="note">Duplicate copies are dropped. Every other flagged row is kept in a quarantine table with its reason, so nothing disappears silently.</p>
{_table(quality.drop(columns=["examples"]))}

<h2>2. Yield</h2>
{_table(kpis["v_yield_by_temperature"])}
<p class="note">Five lots with the lowest first-pass yield:</p>
{_table(worst_lots)}
{chart_station_yield(kpis["v_station_daily"])}

<h2>3. Fail bins (Pareto)</h2>
{_table(kpis["v_bin_pareto"])}
{chart_pareto(kpis["v_bin_pareto"])}

<h2>4. Process control: hot leakage per station</h2>
<p><b>Out-of-control alarms:</b> {html.escape(alarm_text)}</p>
<p class="note">X-bar chart on log(leakage) at 125 degC, limits from each station's first 10 days and adjusted for each day's sample size. An alarm here is a process signal, not a data error: these rows passed every data quality rule.</p>
{control_imgs}

<h2>5. Process capability (first attempts)</h2>
<p class="note">Leakage is skewed (roughly log-normal), so its Cpk is an approximation.</p>
{_table(capability)}
"""
    path = Path(path)
    path.write_text(
        f"<!doctype html><html><head><meta charset='utf-8'><title>MCU Test Report</title><style>{CSS}</style></head><body>{body}</body></html>"
    )
    return path
